---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-auth
  namespace: fission-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fission-auth
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["fission.io"]
  resources: ["functionaccessrules"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fission-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fission-auth
subjects:
- kind: ServiceAccount
  name: fission-auth
  namespace: fission-auth
