apiVersion: v1
kind: Service
metadata:
  name: fission-auth
  namespace: fission-auth
  labels:
    app: fission-auth
spec:
  type: ClusterIP
  selector:
    app: fission-auth
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
